Sidebar
luvi-ui/laravel-luvi pull request #17
Opened 2024-12-25 20:52 UTC by coasterkolja

2025-01-07 17:51 UTC, adiologydev commented
@anotherfrontendguy can you please check this PR? I think it'd be a great addition.

2025-01-08 08:10 UTC, anotherfrontendguy commented
Thanks for your contribution.

We need to provide a guide for users on how to use this component like we do for the others ([see Dialog](https://laravel-luvi.com/docs/components/dialog#usage) for example).

Could you please provide a "maxed-out" usage example?

2025-01-09 07:54 UTC, anotherfrontendguy commented on src/LaravelLuviServiceProvider.php
> +        ], 'searchable');
The second parameter should be sidebar.

2025-01-09 07:55 UTC, anotherfrontendguy commented on resources/js/plugins/sidebar.js
> +            console.log(this.$data.__open);
Drop the `console.log`.

2025-01-09 08:40 UTC, michaelklopf requested changes
Your PR needs to be more rounded and tested. From our point of view the example doesn't work.

To test the sidebar it would be best if you provide a new repository with a fresh Laravel project that makes use of the sidebar. There you can also test and improve it.

A new feature must be realised together with documentation, which is living in this project https://github.com/luvi-ui/website.

When your sidebar is working correctly, you can create the documentation for it, like so
- create a fork from https://github.com/luvi-ui/website
- in a new branch add a section for sidebar similar to the other components
- for testing use your laravel-luvi branch in the website branch and add it under repositories (Composer repositories https://getcomposer.org/doc/05-repositories.md#vcs)
- and for the PR don't commit the composer.json with the repository

You could've provided the example in a comment here. Please remove it from this PR.

2025-01-09 08:40 UTC, michaelklopf commented on composer.json
> +    "name": "coasterkolja/laravel-luvi",
Never change the package name

2025-01-09 08:40 UTC, michaelklopf commented on src/LaravelLuviServiceProvider.php
> +        $this->publishes([
Do not duplicate the publish function when one with 'searchable' already exists.

2025-05-03 13:08 UTC, closed without merging